### ISSUE TITLE
MainRunner Exception Missing value

### ISSUE THREAD

**Issue by C3004** [Daedren/MangaManage#2]
Hello,
i've been fidling around with your program for a bit, but I'm now stuck with this error:

![mangamanage](https://user-images.githubusercontent.com/93786172/178840515-309b20cc-b47e-4881-98ef-c8f22f0283e9.png)

I'm running your latest release(1.2.0) in a custom docker container.
The loglevel is set to debugging so no push notifications should be sent but i haven't defined the key variables for those with real keys. Could that be a cause?

Anyways I'm looking forward to sorting this out.

**Comment by Daedren** [comment]
Hm, from the looks of it, looks like the Anilist token isn't set in the settings? That does look like an error thrown by the UpdateTrackerIds file.
It's needed to set the chapters as read over there (And also to keep track of when series names change when you migrate to other sources on Tachi)

The latest commit in the master branch does have a couple more fixes not in the latest release, but I don't recall that part was touched.

I can look into it in more detail in a few days when I get home if you'd like, I'm currently on a business trip for the $dayJob.

**Comment by C3004** [comment]
Oh wait,
the Reason it isn't working then is probably that i don't have the series added in my anilist account.
The program has more features than i need anyway so i'll see if i can sort this out with my own fork.
Thanks for the answer.

**Comment by Daedren** [comment]
Yeah I need to look into a solution to that myself.
It's been happening to me a few times over very new series (especially Twitter ones and one-shots) that just aren't on MAL or Anilist yet.
