### ISSUE TITLE
sync with anilist question

### ISSUE THREAD

**Issue by imed-ghomari** [Daedren/MangaManage#3]
Haven't tried mangamanage yet, but curious about how you automatically set the last read chapter in anilist while reading a manga on your pc ?

**Comment by Daedren** [comment]
I somehow never got a notification from this comment. 
Not sure if you still need an answer but..

I read the chapters on Komga, if you use the MALSync extension, you can auto-mark them as read. Despite being named that, it works with AniList

**Comment by imed-ghomari** [comment]
okay thanks for clarifying

**Comment by imed-ghomari** [comment]
I'm trying to read with komga and sync with anilist. But I can't find the right custom domain to trigger the automatic tracking. Can you tell me which one you're using ?
